# Generated by Django 6.0 on 2026-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='adderss',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
