# Generated by Django 6.0 on 2026-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentprofile_adderss_studentprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
